services:
  db:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: stardew_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: stardew_user
      POSTGRES_PASSWORD: stardew_pass
      POSTGRES_DB: stardew_db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  pg_data:
